import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  // Screen-Betrieb: Vollbild-Inhalt in MenuScreenShell (kein Fixed-Overlay mehr)
  overlay: {
    display: 'flex', flexDirection: 'column', alignItems: 'center',
  },
  panel: {
    width: '100%', maxWidth: 640,
    background: 'var(--paper-warm)', border: '2.5px solid var(--ink)', borderRadius: 8,
    boxShadow: '6px 6px 0 var(--ink)', padding: 22, color: 'var(--ink)',
  },
  header: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 },
  title: { flex: 1, fontSize: 20, fontWeight: 800, color: 'var(--ink)', margin: 0, textTransform: 'uppercase' as const, letterSpacing: 0.5 },
  headerRight: { display: 'flex', gap: 8, alignItems: 'center' },
  stash: { padding: '6px 12px', background: '#eef7e6', border: '2px solid var(--ink)', borderRadius: 8, boxShadow: '2px 2px 0 var(--ink)', fontSize: 13, fontWeight: 700 },
  closeBtn: { width: 34, height: 34, background: '#fff', border: '2px solid var(--ink)', borderRadius: 8, color: 'var(--ink)', cursor: 'pointer', fontWeight: 800, boxShadow: '2px 2px 0 var(--ink)' },
  desc: { fontSize: 12, color: '#6b6250', margin: '0 0 14px', fontWeight: 600 },
  shareNote: { marginBottom: 10, padding: '8px 10px', background: '#fff', border: '2px solid var(--leaf-dark)', borderRadius: 8, color: 'var(--leaf-dark)', fontSize: 12, fontWeight: 700, wordBreak: 'break-all' as const },
  sowBtn: { width: '100%', padding: 14, fontSize: 15, fontWeight: 800, color: '#fff', background: 'var(--leaf)', border: '2.5px solid var(--ink)', borderRadius: 8, cursor: 'pointer', boxShadow: '3px 3px 0 var(--ink)', marginBottom: 8 },
  parentRow: { display: 'flex', gap: 8, flexWrap: 'wrap' as const, alignItems: 'center', marginBottom: 6 },
  parentCard: { position: 'relative' as const, display: 'flex', alignItems: 'center', gap: 8, padding: '6px 10px', background: '#fff', border: '2px solid var(--ink)', borderRadius: 10, cursor: 'pointer', minHeight: 52, boxShadow: '2px 2px 0 var(--ink)' },
  parentCardActive: { background: '#eef7e6', borderColor: 'var(--leaf-dark)' },
  parentName: { fontSize: 12, fontWeight: 800, color: 'var(--ink)' },
  parentBadge: { position: 'absolute' as const, top: -8, right: -8, width: 22, height: 22, borderRadius: 11, background: 'var(--leaf)', color: '#fff', border: '2px solid var(--ink)', fontSize: 12, fontWeight: 800, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  parentLine: { fontSize: 12, fontWeight: 700, color: '#6b6250', marginBottom: 10 },
  slotBtn: { width: '100%', padding: 11, marginBottom: 6, background: '#fff', border: '2px dashed var(--ink)', borderRadius: 8, color: 'var(--ink)', fontSize: 12, fontWeight: 800, cursor: 'pointer', boxShadow: '2px 2px 0 var(--ink)' },
  hint: { fontSize: 11, color: '#8a8065', marginBottom: 10, fontWeight: 600 },
  helpToggle: { width: '100%', padding: '8px 12px', marginBottom: 10, background: '#fff', border: '1.5px dashed var(--ink)', borderRadius: 8, color: '#6b6250', fontSize: 12, fontWeight: 700, cursor: 'pointer', textAlign: 'center' as const, minHeight: 44 },
  helpBox: { marginBottom: 10, padding: '10px 12px', background: '#f7f3e8', border: '1.5px solid var(--ink)', borderRadius: 8, color: '#4a4437', fontSize: 12, fontWeight: 600, whiteSpace: 'pre-line' as const, lineHeight: 1.55 },
  resultCard: { padding: 16, background: '#fff', border: '2.5px solid var(--ink)', borderRadius: 8, boxShadow: '3px 3px 0 var(--ink)', marginBottom: 14 },
  resultTitle: { fontSize: 12, textTransform: 'uppercase' as const, letterSpacing: 1, color: '#6b6250', marginBottom: 6, fontWeight: 800 },
  childRow: { display: 'flex', gap: 12, alignItems: 'center' },
  childInfo: { flex: 1 },
  childName: { fontSize: 17, color: 'var(--ink)' },
  traitRow: { display: 'flex', gap: 4, flexWrap: 'wrap' as const, marginTop: 4 },
  traitTag: { fontSize: 10, background: '#f0fdf4', color: '#6b6250', padding: '2px 8px', borderRadius: 99, border: '1.5px solid var(--ink)', fontWeight: 700 },
  parentsLine: { fontSize: 12, color: '#6b6250', margin: '10px 0 4px', fontWeight: 600 },
  maturationLine: { fontSize: 12, color: '#8a6d1f', marginBottom: 10, fontWeight: 700 },
  resultActions: { display: 'flex', gap: 8 },
  claimBtn: { flex: 1, padding: 10, background: '#eef7e6', border: '2px solid var(--ink)', borderRadius: 8, color: 'var(--ink)', cursor: 'pointer', fontSize: 13, fontWeight: 800, boxShadow: '2px 2px 0 var(--ink)' },
  shareBtn: { padding: '10px 14px', background: '#fff', border: '2px solid var(--ink)', borderRadius: 8, color: 'var(--ink)', cursor: 'pointer', fontSize: 12, fontWeight: 700, boxShadow: '2px 2px 0 var(--ink)' },
  pendingRow: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  potsRow: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10, marginBottom: 12 },
  pot: { display: 'flex', flexDirection: 'column' as const, alignItems: 'center', gap: 6, padding: 14, background: '#fff', borderWidth: '2.5px', borderStyle: 'dashed', borderColor: 'var(--ink)', borderRadius: 10, cursor: 'pointer', minHeight: 84, boxShadow: '2px 2px 0 var(--ink)' },
  potName: { fontSize: 11, fontWeight: 800, color: 'var(--ink)', textAlign: 'center' as const },
  potEmpty: { fontSize: 11, color: '#8a8065', fontWeight: 700, textAlign: 'center' as const },
  seedlingRow: { display: 'flex', gap: 8, flexWrap: 'wrap' as const, alignItems: 'center', marginBottom: 12 },
  seedling: { padding: '8px 12px', borderWidth: '2px', borderStyle: 'solid', borderColor: 'var(--ink)', borderRadius: 8, cursor: 'pointer', fontSize: 12, fontWeight: 700, color: 'var(--ink)', boxShadow: '2px 2px 0 var(--ink)', minHeight: 44 },
  sectionTitle: { fontSize: 12, color: '#6b6250', textTransform: 'uppercase' as const, letterSpacing: 1, fontWeight: 800 },
  pendingItem: { fontSize: 12, color: '#6b6250', padding: '6px 10px', background: '#fff', border: '1.5px solid var(--ink)', borderRadius: 8, fontWeight: 600 },
  pendingReady: { padding: '10px 12px', background: '#fff', border: '2px solid var(--leaf-dark)', borderRadius: 8 },
};