// Owner: UI (MainMenu-Styles). LOC ≤ 200.
// Reines Präsentations-Styling des Hub-Screens (Paper/Ink-Sprache, B0).
// Kein State, keine Logik — nur die CSS-Objekte, die MainMenu konsumiert.
// Ausgelagert aus MainMenu.tsx (Mischlogik Präsentation/Komponente — Godfile-Audit).
import type { CSSProperties } from 'react';

export const mainMenuStyles: Record<string, CSSProperties> = {
  marquee: {
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    background: 'var(--ink)',
    color: 'var(--nektar)',
    fontFamily: 'ui-monospace, Menlo, monospace',
    fontSize: 11,
    letterSpacing: 1,
    padding: '5px 8px',
    borderRadius: 4,
    marginBottom: 16,
    textOverflow: 'ellipsis',
  },
  statsRow: {
    display: 'flex',
    gap: 12,
    marginBottom: 18,
  },
  statBox: {
    flex: 1,
    padding: '10px 14px',
    background: '#fff',
    border: '2px solid var(--ink)',
    borderRadius: 8,
    boxShadow: '3px 3px 0 var(--ink)',
    textAlign: 'center',
    transform: 'rotate(-0.4deg)',
  },
  statValue: {
    fontSize: 22,
    fontWeight: 800,
    color: 'var(--leaf-dark)',
  },
  statLabel: {
    fontSize: 11,
    color: '#6b6250',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: 2,
    fontWeight: 700,
  },
  modes: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 14,
    marginBottom: 22,
  },
  modeCard: {
    position: 'relative',
    textAlign: 'left',
    padding: 16,
    background: '#fff',
    border: '2.5px solid var(--ink)',
    borderRadius: 6,
    boxShadow: '4px 4px 0 var(--ink)',
    cursor: 'pointer',
    transition: 'transform 0.08s',
    color: 'var(--ink)',
    minHeight: 44,
  },
  modeCardHighlight: {
    background: '#eef7e6',
    borderColor: 'var(--leaf-dark)',
    boxShadow: '4px 4px 0 var(--leaf-dark)',
    transform: 'rotate(0.4deg)',
  },

  modeCardNest: {
    background: 'var(--paper-warm)',
    border: '2.5px solid var(--ink)',
    boxShadow: '4px 4px 0 var(--ink)',
  },
  modeCardNestHeader: {
    background: 'repeating-linear-gradient(90deg, var(--bloom) 0 8px, var(--paper-dim) 8px 16px)',
    height: '14px',
  },
  modeCardDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
  },
  modeIcon: {
    marginBottom: 8,
  },
  modeTitle: {
    fontSize: 15,
    fontWeight: 800,
    marginBottom: 4,
  },
  modeDesc: {
    fontSize: 12,
    color: '#6b6250',
    lineHeight: 1.4,
    fontWeight: 600,
  },
  collectionSection: {
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 12,
    color: '#6b6250',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 10,
    fontWeight: 800,
  },
  collectionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
    gap: 8,
  },
  collectionItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    background: '#fff',
    border: '2px solid var(--ink)',
    borderRadius: 6,
    boxShadow: '2px 2px 0 var(--ink)',
    fontSize: 12,
    color: 'var(--ink)',
    fontWeight: 600,
    cursor: 'pointer',
    minHeight: 44,
  },
  loadoutItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    background: '#eef7e6',
    border: '2px solid var(--leaf-dark)',
    borderRadius: 6,
    boxShadow: '2px 2px 0 var(--leaf-dark)',
    fontSize: 12,
    color: 'var(--ink)',
    fontWeight: 600,
    cursor: 'pointer',
    minHeight: 44,
  },
  loadoutFull: {
    opacity: 0.45,
    cursor: 'not-allowed',
  },
  /** Rahmen um die Pflanzen-Kachel (B27): das Bild kommt aus `PlantVariantThumb`. */
  thumb: {
    flexShrink: 0,
    display: 'block',
    lineHeight: 0,
  },
  name: {
    flex: 1,
    color: 'var(--ink)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  count: {
    color: '#6b6250',
    fontSize: 11,
    fontWeight: 800,
  },
  empty: {
    color: '#6b6250',
    fontSize: 13,
    padding: 12,
  },
  footer: {
    marginTop: 18,
    paddingTop: 10,
    borderTop: '1.5px dashed #b7ab8d',
    fontSize: 11,
    color: '#8a8065',
    fontStyle: 'italic',
  },
};
